# Generated by Django 4.2 on 2023-04-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todo_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todoitems',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
